//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerInformatica1_WebService.ServiceReferencesumaNumeros {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencesumaNumeros.WebService_SumaNumerosSoap")]
    public interface WebService_SumaNumerosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumaNumeros", ReplyAction="*")]
        int sumaNumeros(int primerNumero, int segundoNumero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumaNumeros", ReplyAction="*")]
        System.Threading.Tasks.Task<int> sumaNumerosAsync(int primerNumero, int segundoNumero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_SumaNumerosSoapChannel : TallerInformatica1_WebService.ServiceReferencesumaNumeros.WebService_SumaNumerosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_SumaNumerosSoapClient : System.ServiceModel.ClientBase<TallerInformatica1_WebService.ServiceReferencesumaNumeros.WebService_SumaNumerosSoap>, TallerInformatica1_WebService.ServiceReferencesumaNumeros.WebService_SumaNumerosSoap {
        
        public WebService_SumaNumerosSoapClient() {
        }
        
        public WebService_SumaNumerosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_SumaNumerosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_SumaNumerosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_SumaNumerosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sumaNumeros(int primerNumero, int segundoNumero) {
            return base.Channel.sumaNumeros(primerNumero, segundoNumero);
        }
        
        public System.Threading.Tasks.Task<int> sumaNumerosAsync(int primerNumero, int segundoNumero) {
            return base.Channel.sumaNumerosAsync(primerNumero, segundoNumero);
        }
    }
}
